name: CI
on:
  push:
    branches: [ main, dev/* ]
  pull_request:
    branches: [ main, dev/* ]

jobs:
  Quality:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        poetry-version: [1.2.2]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install packages
        run: |
          poetry install
      - name: Style Checks
        run: |
          poetry run style

  Release:
    needs: Quality
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, 'chore(release):')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0
      - name: Install Semantic Release
        run: |
          pip install python-semantic-release==7.28.1
      - name: Set git config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Publish
        run: |
          semantic-release publish
